# Dependencies
#markdown:         redcarpet
#highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            TSheets
tagline:          'Web Application Style Guide'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://tsheets.com
baseurl:          "" # the subpath of your site, e.g. /blog

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

# Build settings
markdown: kramdown

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
