# Dependencies
#markdown:         redcarpet
#highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            TSheets
tagline:          'Web Application Style Guide'
description:      'Style Guide'
url:              http://justinhersey.github.io/
baseurl: "/style-guides" # the subpath of your site, e.g. /blog

author:
  name:           'TSheets'
  url:            http://tsheets.com

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/justinhersey/style-guides/tree/gh-pages

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Collections
collections:
  components:
    output: false
