# Dependencies
#markdown:         redcarpet
#highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            TSheets
tagline:          'Web Application Style Guide'
description:      ''
url:              http://justinhersey.github.io/
baseurl: "/style-guides/" # the subpath of your site, e.g. /blog

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
